//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Harsh/Scripts/Player/InputMapping.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMapping: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMapping()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMapping"",
    ""maps"": [
        {
            ""name"": ""MovementMap"",
            ""id"": ""d5dc90b2-f2d7-4478-bb22-577eaeb5cfa1"",
            ""actions"": [
                {
                    ""name"": ""LongMovement"",
                    ""type"": ""Button"",
                    ""id"": ""9beeab60-9941-4373-bc86-dd69884f9782"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LateralMovement"",
                    ""type"": ""Button"",
                    ""id"": ""4be6cad3-58aa-438c-be50-e9c7dcf83dab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""261af3a1-3472-4d96-8e5a-3daf6f344072"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""a9c778fd-586f-4c01-bf70-6c07542d42f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Button"",
                    ""id"": ""76bc668d-ecdc-4ccc-b150-c30e9113409e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LookHorizontal"",
                    ""type"": ""Button"",
                    ""id"": ""9affed28-1e0c-4aff-ba5d-8b8cd8610bbc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LookVertical"",
                    ""type"": ""Button"",
                    ""id"": ""d08ff1de-d0a9-4365-8fe7-60dcb8cdc91c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextDialog"",
                    ""type"": ""Button"",
                    ""id"": ""e7769b02-5057-4775-ae3d-f4daca062193"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""4d5a5f3e-e2a8-418a-b3a2-2f592231b8a4"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LongMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""8bb2ccb4-8505-49ff-87f5-9bc2b2a8ca35"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LongMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""41200411-6f24-415a-893d-aab96bc1a04b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LongMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""42784772-92b6-4770-aef5-c8848b46efb6"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LateralMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c511f3f2-ac95-4da7-80cc-54dab34ef014"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LateralMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2f7ab563-2bb9-4439-8a3e-9551dc186bf8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LateralMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4d11ddfb-ab04-4ce5-b49e-51e20cc98731"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b2f3eb1-a971-4bf1-94ee-0cf28d1be69b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9cac969-b2db-4dca-a481-45f7a27fd63d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""e505d209-a571-43e9-a711-cbd3e9279bd6"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookHorizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6aecdfd7-74b2-40dd-b525-84d34afb6c5c"",
                    ""path"": ""<Mouse>/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""cfeba095-8b6b-4163-ab4e-a03d1bb3851b"",
                    ""path"": ""<Mouse>/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""c554b80d-750b-43ef-8093-6b9fbcd1fbfb"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookVertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""66c0ae0b-f5f8-430c-a4c8-7a62ef017cf3"",
                    ""path"": ""<Mouse>/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""708f6cfa-50c4-44ef-a102-9cb9512e7e96"",
                    ""path"": ""<Mouse>/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fb5c7cbb-aa20-479f-a345-45e62fe0235d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextDialog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MovementMap
        m_MovementMap = asset.FindActionMap("MovementMap", throwIfNotFound: true);
        m_MovementMap_LongMovement = m_MovementMap.FindAction("LongMovement", throwIfNotFound: true);
        m_MovementMap_LateralMovement = m_MovementMap.FindAction("LateralMovement", throwIfNotFound: true);
        m_MovementMap_Jump = m_MovementMap.FindAction("Jump", throwIfNotFound: true);
        m_MovementMap_Interact = m_MovementMap.FindAction("Interact", throwIfNotFound: true);
        m_MovementMap_Zoom = m_MovementMap.FindAction("Zoom", throwIfNotFound: true);
        m_MovementMap_LookHorizontal = m_MovementMap.FindAction("LookHorizontal", throwIfNotFound: true);
        m_MovementMap_LookVertical = m_MovementMap.FindAction("LookVertical", throwIfNotFound: true);
        m_MovementMap_NextDialog = m_MovementMap.FindAction("NextDialog", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MovementMap
    private readonly InputActionMap m_MovementMap;
    private List<IMovementMapActions> m_MovementMapActionsCallbackInterfaces = new List<IMovementMapActions>();
    private readonly InputAction m_MovementMap_LongMovement;
    private readonly InputAction m_MovementMap_LateralMovement;
    private readonly InputAction m_MovementMap_Jump;
    private readonly InputAction m_MovementMap_Interact;
    private readonly InputAction m_MovementMap_Zoom;
    private readonly InputAction m_MovementMap_LookHorizontal;
    private readonly InputAction m_MovementMap_LookVertical;
    private readonly InputAction m_MovementMap_NextDialog;
    public struct MovementMapActions
    {
        private @InputMapping m_Wrapper;
        public MovementMapActions(@InputMapping wrapper) { m_Wrapper = wrapper; }
        public InputAction @LongMovement => m_Wrapper.m_MovementMap_LongMovement;
        public InputAction @LateralMovement => m_Wrapper.m_MovementMap_LateralMovement;
        public InputAction @Jump => m_Wrapper.m_MovementMap_Jump;
        public InputAction @Interact => m_Wrapper.m_MovementMap_Interact;
        public InputAction @Zoom => m_Wrapper.m_MovementMap_Zoom;
        public InputAction @LookHorizontal => m_Wrapper.m_MovementMap_LookHorizontal;
        public InputAction @LookVertical => m_Wrapper.m_MovementMap_LookVertical;
        public InputAction @NextDialog => m_Wrapper.m_MovementMap_NextDialog;
        public InputActionMap Get() { return m_Wrapper.m_MovementMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementMapActions set) { return set.Get(); }
        public void AddCallbacks(IMovementMapActions instance)
        {
            if (instance == null || m_Wrapper.m_MovementMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MovementMapActionsCallbackInterfaces.Add(instance);
            @LongMovement.started += instance.OnLongMovement;
            @LongMovement.performed += instance.OnLongMovement;
            @LongMovement.canceled += instance.OnLongMovement;
            @LateralMovement.started += instance.OnLateralMovement;
            @LateralMovement.performed += instance.OnLateralMovement;
            @LateralMovement.canceled += instance.OnLateralMovement;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
            @LookHorizontal.started += instance.OnLookHorizontal;
            @LookHorizontal.performed += instance.OnLookHorizontal;
            @LookHorizontal.canceled += instance.OnLookHorizontal;
            @LookVertical.started += instance.OnLookVertical;
            @LookVertical.performed += instance.OnLookVertical;
            @LookVertical.canceled += instance.OnLookVertical;
            @NextDialog.started += instance.OnNextDialog;
            @NextDialog.performed += instance.OnNextDialog;
            @NextDialog.canceled += instance.OnNextDialog;
        }

        private void UnregisterCallbacks(IMovementMapActions instance)
        {
            @LongMovement.started -= instance.OnLongMovement;
            @LongMovement.performed -= instance.OnLongMovement;
            @LongMovement.canceled -= instance.OnLongMovement;
            @LateralMovement.started -= instance.OnLateralMovement;
            @LateralMovement.performed -= instance.OnLateralMovement;
            @LateralMovement.canceled -= instance.OnLateralMovement;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
            @LookHorizontal.started -= instance.OnLookHorizontal;
            @LookHorizontal.performed -= instance.OnLookHorizontal;
            @LookHorizontal.canceled -= instance.OnLookHorizontal;
            @LookVertical.started -= instance.OnLookVertical;
            @LookVertical.performed -= instance.OnLookVertical;
            @LookVertical.canceled -= instance.OnLookVertical;
            @NextDialog.started -= instance.OnNextDialog;
            @NextDialog.performed -= instance.OnNextDialog;
            @NextDialog.canceled -= instance.OnNextDialog;
        }

        public void RemoveCallbacks(IMovementMapActions instance)
        {
            if (m_Wrapper.m_MovementMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMovementMapActions instance)
        {
            foreach (var item in m_Wrapper.m_MovementMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MovementMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MovementMapActions @MovementMap => new MovementMapActions(this);
    public interface IMovementMapActions
    {
        void OnLongMovement(InputAction.CallbackContext context);
        void OnLateralMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnLookHorizontal(InputAction.CallbackContext context);
        void OnLookVertical(InputAction.CallbackContext context);
        void OnNextDialog(InputAction.CallbackContext context);
    }
}
